polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/ordersOnly/
    url(r'^ordersOnly/$', views.OrdersOnlyView.as_view(), name='ordersOnly'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /polls/assets/
    url(r'^assets/$', views.AssetList.as_view(), name='assets-list'),
    # ex: /polls/assets/new/
    url(r'^assets/new/$', views.AssetCreate.as_view(), name='assets-new'),
    # ex: /polls/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', views.AssetDelete.as_view(), name='assets-delete'),

]

zipline/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

zipline_app/urls.py
from django.conf.urls import url

from .views.zipline_app import zipline_app as views
from .views.zipline_app import blotter
from .views.zipline_app import order, asset, fill, account, autocomplete
from django.contrib.auth import views as auth_views

app_name='zipline_app'
urlpatterns = [
    # ex: /<root>/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /<root>/blotter/sideBySide
    url(r'^blotter/sideBySide/$', blotter.BlotterSideBySideView.as_view(), name='blotter-sideBySide'),
    # ex: /<root>/blotter/engine/
    url(r'^blotter/engine/$', blotter.BlotterEngineView.as_view(), name='blotter-engine'),
    # ex: /<root>/blotter/concealed/
    url(r'^blotter/concealed/$', blotter.BlotterConcealedView.as_view(), name='blotter-concealed'),
    # ex: /<root>/blotter/download/
    url(r'^blotter/download/$', blotter.BlotterDownloadView.as_view(), name='blotter-download'),

    # ex: /<root>/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /<root>/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /<root>/accounts/
    url(r'^accounts/$', account.AccountList.as_view(), name='accounts-list'),
    # ex: /<root>/accounts/new/
    url(r'^accounts/new/$', account.AccountCreate.as_view(), name='accounts-new'),
    # ex: /<root>/accounts/5/
    url(r'^accounts/(?P<pk>[0-9]+)/$', account.AccountDetailView.as_view(), name='accounts-detail'),
    # ex: /<root>/accounts/1/update/
    url(r'^accounts/(?P<pk>[0-9]+)/update/$', account.AccountUpdateView.as_view(), name='accounts-update'),
    # ex: /<root>/accounts/1/delete/
    url(r'^accounts/(?P<pk>[0-9]+)/delete/$', account.AccountDelete.as_view(), name='accounts-delete'),

    # ex: /<root>/assets/
    url(r'^assets/$', asset.AssetList.as_view(), name='assets-list'),
    # ex: /<root>/assets/new/
    url(r'^assets/new/$', asset.AssetCreate.as_view(), name='assets-new'),
    # ex: /<root>/assets/5/
    url(r'^assets/(?P<pk>[0-9]+)/$', asset.AssetDetailView.as_view(), name='assets-detail'),
    # ex: /<root>/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', asset.AssetDelete.as_view(), name='assets-delete'),
    # ex: /<root>/assets/1/update/
    url(r'^assets/(?P<pk>[0-9]+)/update/$', asset.AssetUpdateView.as_view(), name='assets-update'),

    # ex: /<root>/fills/
    url(r'^fills/$', fill.FillList.as_view(), name='fills-list'),
    # ex: /<root>/fills/5/
    url(r'^fills/(?P<pk>[0-9]+)/$', fill.FillDetailView.as_view(), name='fills-detail'),
    # ex: /<root>/fills/new/
    url(r'^fills/new/$', fill.FillCreate.as_view(), name='fills-new'),
    # ex: /<root>/fills/1/update/
    url(r'^fills/(?P<pk>[0-9]+)/update/$', fill.FillUpdateView.as_view(), name='fills-update'),
    # ex: /<root>/fills/1/delete/
    url(r'^fills/(?P<pk>[0-9]+)/delete/$', fill.FillDelete.as_view(), name='fills-delete'),

    # ex: /<root>/orders/
    url(r'^orders/$', order.OrderList.as_view(), name='orders-list'),
    # ex: /<root>/orders/5/
    url(r'^orders/(?P<pk>[0-9]+)/$', order.OrderDetailView.as_view(), name='orders-detail'),
    # ex: /<root>/orders/new/
    url(r'^orders/new/$', order.OrderCreate.as_view(), name='orders-new'),
    # ex: /<root>/orders/1/delete/
    url(r'^orders/(?P<pk>[0-9]+)/delete/$', order.OrderDelete.as_view(), name='orders-delete'),
    # ex: /<root>/orders/5/update/
    url(r'^orders/(?P<pk>[0-9]+)/update/$', order.OrderUpdateView.as_view(), name='orders-update'),

    # Autocomplete Input Field In Django Template with Jquery-UI
    # http://blog.appliedinformaticsinc.com/autocomplete-input-field-in-django-template-with-jquery-ui/
    url(r'^autocomplete/asset/$',   autocomplete.AutoCompleteAssetView.as_view(),   name='autocomplete-asset'),
    url(r'^autocomplete/account/$', autocomplete.AutoCompleteAccountView.as_view(), name='autocomplete-account'),

    # user login
    # https://docs.djangoproject.com/en/1.10/topics/auth/default/#the-login-required-decorator
    url(r'^users/login/$', auth_views.login, name='login'),
    url(r'^users/logout/$', auth_views.logout, name='logout'),
]

zipline_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('zipline_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
]

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime

from zipline.finance.execution import (
    LimitOrder,
    MarketOrder,
    StopLimitOrder,
    StopOrder,
)

from .matcher import factory as mmm_factory, Matcher as mmm_Matcher
import pandas as pd
from six import iteritems
from functools import reduce

import json
import hashlib
from numpy import average, concatenate
from django.db import connection

# Django Logging
# https://docs.djangoproject.com/en/1.10/topics/logging/
import logging
logger = logging.getLogger(__name__)

from django.urls import reverse

# Create your models here.

def md5_wrap(string):
  return hashlib.md5(string.encode('utf-8')).hexdigest()

class Asset(models.Model):
    asset_symbol = models.CharField(max_length=20)
    asset_exchange = models.CharField(max_length=200)
    asset_name = models.CharField(max_length=200)

    def __str__(self):
        return "%s, %s, %s" % (self.asset_symbol, self.asset_exchange, self.asset_name)

    def to_dict(self):
        return {
          "symbol": self.asset_symbol,
          "exchange": self.asset_exchange,
          "name": self.asset_name
        }

    def get_absolute_url(self):
      return reverse('polls:assets-list')
#      return reverse('polls:assets-list', kwargs={'pk': self.pk})


class Account(models.Model):
    account_symbol = models.CharField(max_length=20)
    def __str__(self):
      return self.account_symbol
 
class Order(models.Model):
    order_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, null=True)
    amount = models.IntegerField(default=0)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    # static variable

    def __str__(self):
        return "%s, %s (%s, %s)" % (self.asset.asset_symbol, self.amount, self.account.account_symbol, self.order_text)

    def md5(self):
        string = "%s, %s, %s (%s, %s)" % (self.pub_date, self.asset.asset_symbol, self.amount, self.account.account_symbol, self.order_text)
        return md5_wrap(string)

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

    def filled(self):
      if self.id in ZlModel.zl_closed_keyed:
        return self.amount
      if self.id in ZlModel.zl_open_keyed:
        return ZlModel.zl_open_keyed[self.id].filled
      return 0

    def fills(self):
      return [txn for txn in ZlModel.zl_txns if txn["order_id"]==self.id]

    def avgPrice(self):
      if self.filled()==0:
        return float('nan')

      sub = self.fills()
      avg = average(a=[txn["price"] for txn in sub], weights=[txn["amount"] for txn in sub])
      return avg

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Fill(models.Model):
    # 2017-01-12: unlink orders from fills and use zipline engine to perform matching
    # order = models.ForeignKey(Order, on_delete=models.CASCADE)
    fill_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    fill_qty = models.IntegerField(default=0)
    fill_price = models.FloatField(default=0)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "%s, %s, %s (%s)" % (self.asset.asset_symbol, self.fill_qty, self.fill_price, self.fill_text)

    def md5(self):
        string = "%s, %s, %s, %s (%s)" % (self.pub_date, self.asset.asset_symbol, self.fill_qty, self.fill_price, self.fill_text)
        return md5_wrap(string)

    def has_unused(self):
      return self.asset.id in ZlModel.zl_unused

class ZlModel:
    md5 = None
    zl_open       = []
    zl_closed     = []
    zl_txns       = []
    zl_open_keyed = {}
    zl_closed_keyed = {}
    fills={}
    orders={}
    assets={}
    zl_unused = {}

    @staticmethod
    def clear():
      ZlModel.md5 = None
      ZlModel.zl_open       = []
      ZlModel.zl_closed     = []
      ZlModel.zl_txns       = []
      ZlModel.zl_open_keyed = {}
      ZlModel.zl_closed_keyed = {}
      ZlModel.fills={}
      ZlModel.orders={}
      ZlModel.assets={}
      ZlModel.zl_unused = {}

    @staticmethod
    def add_asset(asset: Asset):
      #print("adding asset",asset,asset.id)
      ZlModel.assets[asset.id]=asset.to_dict()

    @staticmethod
    def add_fill(fill: Fill):
      #print("Adding fill: %s" % fill)
      if fill.asset.id not in ZlModel.fills:
        ZlModel.fills[fill.asset.id]={}

      ZlModel.fills[fill.asset.id][fill.id]={
        "close": fill.fill_price,
        "volume": fill.fill_qty,
        "dt": pd.Timestamp(fill.pub_date,tz='utc')
      }

    @staticmethod
    def fills_as_dict_df():
      # Copy keys to a new dictionary (Python)
      # http://stackoverflow.com/a/7369284/4126114
      fills2=dict.fromkeys(ZlModel.fills.keys(),{})

      for sid in ZlModel.fills:
        fills2[sid] = pd.DataFrame({})
        sub = ZlModel.fills[sid].values()
        fills2[sid]["close"]=[y["close"] for y in sub]
        fills2[sid]["volume"]=[y["volume"] for y in sub]
        fills2[sid]["dt"]=[y["dt"] for y in sub]
        fills2[sid]=fills2[sid].set_index("dt")
      return fills2

    @staticmethod
    def add_order(order: Order):
      if order.asset.id not in ZlModel.orders:
        ZlModel.orders[order.asset.id]={}

      ZlModel.orders[order.asset.id][order.id] = {
        "dt": order.pub_date,
        "asset": order.asset.id,
        "amount": order.amount,
        "style": MarketOrder()
      }

    @staticmethod
    def delete_asset(asset: Asset):
      ZlModel.assets.pop(asset.id, None)

    @staticmethod
    def delete_fill(fill: Fill):
      # How to remove a key from a python dictionary
      # http://stackoverflow.com/questions/11277432/ddg#11277439
      ZlModel.fills[fill.asset.id].pop(fill.id, None)
      if not any(ZlModel.fills[fill.asset.id]):
        ZlModel.fills.pop(fill.asset.id, None)

    @staticmethod
    def delete_order(order: Order):
      # How to remove a key from a python dictionary
      # http://stackoverflow.com/questions/11277432/ddg#11277439
      ZlModel.orders.pop(order.id, None)

    @staticmethod
    def db_ready():
      tables = connection.introspection.table_names()
      isready = "polls_fill" in tables
      if not isready:
        logger.debug("db tables not available .. skipping zlmodel init")
      return isready

    @staticmethod
    def init():
      if not ZlModel.db_ready():
        return

      for fill in Fill.objects.all():
        ZlModel.add_fill(fill)
      for order in Order.objects.all():
        ZlModel.add_order(order)
      for asset in Asset.objects.all():
        ZlModel.add_asset(asset)

    @staticmethod
    def update():
      if not ZlModel.db_ready():
        return

      md5 = md5_wrap(json.dumps({
        "fills":[x.md5() for x in Fill.objects.all()],
        "orders":[x.md5() for x in Order.objects.all()],
        "assets":{x.id: x.to_dict() for x in Asset.objects.all()},
      }))

      if ZlModel.md5==md5:
        logger.debug("Model unchanged .. not rerunning engine: "+md5)
        return

      logger.debug("Run matching engine: "+md5)

      matcher = mmm_Matcher()

      all_closed, all_txns, open_orders, ZlModel.zl_unused, ZlModel.all_minutes = mmm_factory(
        matcher,
        ZlModel.fills_as_dict_df(),
        ZlModel.orders,
        ZlModel.assets
      )

      ZlModel.zl_open = reduce(
        lambda a, b: concatenate((a,b)),
        [v for k,v in open_orders.items()],
        list()
      )
      ZlModel.zl_closed = all_closed
      ZlModel.zl_txns = [txn.to_dict() for txn in all_txns]
      ZlModel.zl_open_keyed = {v.id: v for v in ZlModel.zl_open}
      ZlModel.zl_closed_keyed = {v.id: v for v in ZlModel.zl_closed}

      # save md5 at the end to ensure re-run if error occured
      ZlModel.md5=md5


# https://docs.djangoproject.com/en/1.11/topics/signals/#connecting-receiver-functions
#from django.core.signals import request_started
#request_started.connect(ZlModel.update)

# connecting signals
from django.db.backends.signals import connection_created
class SignalProcessor:
  #def post_init(sender, **kwargs):
  #  print("Signal: %s, %s" % ("post_init", sender.__name__))

  def update_if_mine(sender):
    condition = sender.__name__=="Fill" or sender.__name__=="Order" or sender.__name__=="Asset"
    if condition:
      ZlModel.update()

  def post_save(sender, instance, **kwargs):
    #logger.debug("Signal: %s, %s" % ("post_save", sender))
    if sender.__name__=="Fill": ZlModel.add_fill(instance)
    if sender.__name__=="Order": ZlModel.add_order(instance)
    if sender.__name__=="Asset": ZlModel.add_asset(instance)
    SignalProcessor.update_if_mine(sender)

  def post_delete(sender, instance, **kwargs):
    #print("Signal: %s, %s" % ("post_delete", sender))
    if sender.__name__=="Fill": ZlModel.delete_fill(instance)
    if sender.__name__=="Order": ZlModel.delete_order(instance)
    if sender.__name__=="Asset": ZlModel.delete_asset(instance)
    SignalProcessor.update_if_mine(sender)

  def connection_created(sender, **kwargs):
  #  print("Signal: %s, %s" % ("connection_created", sender))
    ZlModel.init()
    ZlModel.update()

senders=("polls.Order", "polls.Fill", "polls.Asset")
for sender in senders:
  #models.signals.post_init.connect(SignalProcessor.post_init, sender=sender)
  models.signals.post_save.connect(SignalProcessor.post_save, sender=sender)
  models.signals.post_delete.connect(SignalProcessor.post_delete, sender=sender)
connection_created.connect(SignalProcessor.connection_created)

zipline_app/forms.py
from .models.zipline_app.fill import Fill
from .models.zipline_app.order import Order
from .widgets import AssetModelSelect2Widget, AccountModelSelect2Widget
from django import forms

# override widget in createview
# http://stackoverflow.com/a/21407374/4126114
# Override a Django generic class-based view widget
# http://stackoverflow.com/a/27322032/4126114
class FillForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Fill
    fields = [
      'pub_date', 'asset', 'fill_side', 'fill_qty_unsigned', 'fill_price', 'fill_text', 'tt_order_key',
      'dedicated_to_order'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget()
    }

class OrderForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Order
    fields = [
      'pub_date', 'asset', 'order_side', 'order_qty_unsigned', 'account', 'order_text',
      'order_type', 'limit_price', 'order_validity', 'validity_date'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget(),
      'account': AccountModelSelect2Widget(),
    }

zipline_app/templates/zipline_app/_index_fills.html
{% load humanize %}
{% load bootstrap3 %}

{% for fill in duo.fills %}
<div class="row {% if fill.has_unused %}text-danger{% endif %}">
  <div class="col-xs-4 text-primary text-right">
    {{fill.fill_side}}
    {{fill.fill_qty_unsigned}}
  </div>
  <div class="col-xs-4 text-primary text-right">{{fill.fill_price}}</div>
  <div class="col-xs-4">
    <div class="row">

      <div class="col-xs-6">
        {% if fill.has_unused %}
        <abbr title="Asset has unmatched fills">
          <span class="glyphicon glyphicon-alert"></span>
        </abbr>
        {% endif %}
      </div>

      <div class="col-xs-6 text-right">
        <abbr title="Fill">
          <a href="{% url 'zipline_app:fills-detail' fill.id %}">
            #{{fill.id}}
          </a>
        </abbr>

      </div>

    </div>
  </div>
</div>
{%if fill.fill_text or fill.tt_order_key %}
<div class="row text-muted">
  <div class="col-xs-4 text-left">{{ fill.tt_order_key }}</div>
  <div class="col-xs-8 text-right">{{ fill.fill_text }}</div>
</div>
{% endif %}
{% endfor %}

zipline_app/templates/zipline_app/asset_form.html
{% extends "zipline_app/base.html" %}

{% block content %}
{% include "zipline_app/_asset_form.html" %}
{% endblock %}

zipline_app/templates/zipline_app/asset_list.html
{% extends "zipline_app/base.html" %}


{% block content %}
<h1>Assets</h1>

<a href="{% url 'zipline_app:assets-new' %}">New</a>

<ul>
    {% for asset in asset_list %}
    <li>
      {{ asset.id }},
      {{ asset.asset_symbol }},
      {{ asset.asset_name }},
      {{ asset.asset_exchange }},
      <a href="{% url 'zipline_app:assets-delete' asset.id %}">Delete</a>
    </li>
{% empty %}
    <li>No assets yet.</li>
{% endfor %}

{% include "zipline_app/_asset_form.html" %}

<div id="MESSAGE-DIV"></div>

<script type="text/javascript">
    var frm = $('#FORM-ID');
    frm.each(function() { this.reset() });
    frm.submit(function () {
       $("#MESSAGE-DIV").html("Loading...");
       $("#FORM-ID :input").prop('disabled', true);
        $.ajax({
            type: frm.attr('method'),
            url: "{% url 'zipline_app:assets-new' %}", //frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                // $("#SOME-DIV").html(data);
                location.reload();
            },
            error: function(data) {
               $("#MESSAGE-DIV").html("Something went wrong: "+data.responseText);
               $("#FORM-ID :input").prop('disabled', false);
            }
        });
        return false;
    });
</script>

{% endblock %}

zipline_app/templates/zipline_app/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load static %}
{% load tz %}

<html lang="en">
<head>
  <!-- http://getbootstrap.com/getting-started/#template -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery=1 %}

  <!-- http://blog.appliedinformaticsinc.com/autocomplete-input-field-in-django-template-with-jquery-ui/
       Autocomplete Input Field In Django Template with Jquery-UI
       -->
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" type="text/css" media="all"/>
  <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js" type="text/javascript"></script>

  <title>Blotter</title>
</head>

<body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'zipline_app:index' %}">
            FFA
          </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'zipline_app:blotter-concealed' %}">Blotter</a></li>
            <li><a href="{% url 'zipline_app:accounts-list' %}">Clients</a></li>
            <li><a href="{% url 'zipline_app:assets-list' %}">Assets</a></li>
            <li><a href="{% url 'zipline_app:orders-list' %}">Orders</a></li>
            <li><a href="{% url 'zipline_app:fills-list' %}">Fills</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% if request.user.username %}
            <li>
              <form action="{% url 'zipline_app:logout' %}" class='form'>
                <input type="hidden" name="next" value="{% url 'zipline_app:index' %}">
                <button type="submit" class='btn btn-default'>Log out from {{request.user.username}}</button>
              </form>
            </li>
            {% endif %}
            {% if request.user.is_authenticated == False %}
            <li><a href="{% url 'zipline_app:login' %}">Login</a></li>
            {% endif %}

          </ul>

          <!-- http://getbootstrap.com/components/#navbar-links -->
          <div class="nav navbar-nav navbar-right navbar-text">
            <div class="row">
              <div class="col-xs-6">
                {% get_current_timezone as TIME_ZONE %}
                {{TIME_ZONE}}
              </div>
              <div class="col-xs-6">
                <a href="http://github.com/shadiakiki1986/django-zipline/" target="_blank">
                  <img src="{% static 'zipline_app/images/github-icon.png' %}" alt="github" width="30px" />
                </a>
              </div>
            </div>
          </div>

        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <!--
      Bootstrap CSS Active Navigation
      http://stackoverflow.com/a/13189166/4126114
    -->
    <script type="text/javascript">
      path = document.location.pathname
      path = "/"+path.split('/')[1]+"/"
      $('.navbar-nav li.active').removeClass('active');
      $('.navbar-nav > li > a[href="' + path + '"]').parent().addClass('active');
    </script>

    <div class="container-fluid">
      <div>
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
      </div>

      <div>
          {% block content %}{% endblock %}
      </div>
    </div>

</body>

</html>

zipline_app/templates/zipline_app/detail.html
{% extends "zipline_app/base.html" %}
{% load humanize %}

{% block content %}
<h1>{{ order.order_text }}</h1>

Order Details
<ul>
  <li>{{order.asset.asset_symbol}}</li>
  <li><font color="red">{{order.filled|intcomma}}</font> / {{order.amount|intcomma}}</li>
  <li>{{order.pub_date}}</li>
  <li>{{order.account.account_symbol}}</li>
  <li>{{ order.order_text }}</li>
</ul>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<font color="red">
{% if order.fills|length > 0 %}
    Current fills
    <ul>
    {% for fill in order.fills %}
        <li>
          {{fill.dt}}:
          {{fill.sid.symbol}},
          {{fill.amount|intcomma}},
          {{fill.price|intcomma}}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No fills are available.</p>
{% endif %}
</font>

Fill
<form action="{% url 'zipline_app:vote' order.id %}" method="post">
{% csrf_token %}
{% for fill in order.fill_set.all %}
    <input type="radio" name="fill" id="fill{{ forloop.counter }}" value="{{ fill.id }}" />
    <label for="fill{{ forloop.counter }}">
       {{fill.fill_qty}},
       {{fill.fill_price}},
       {{ fill.fill_text }}
    </label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}

zipline_app/templates/zipline_app/index.html
{% extends "zipline_app/base.html" %}
{% load humanize %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
This is the electronic blotter for FFA Dubai
{% endblock %}

zipline_app/templates/zipline_app/reminder.html
{% load humanize %}

{{pending|length}} pending order{{num_pending|pluralize}} in <a href="{{domain}}{% url 'zipline_app:blotter-concealed' %}">blotter</a>

{% for order in pending %}
{% ifchanged order.pub_date.date %}
<h3>{{order.pub_date.date|date:"Y-m-d"}}</h3>
{% endifchanged %}
<div>
  <a href="{{domain}}{% url 'zipline_app:orders-detail' order.id %}">#{{order.id}}</a>:
  {{order.get_order_side_display}}
  {{order.order_qty_unsigned|intcomma}} x
  {{order.asset.asset_name}}
  {% if order.order_text %}({{ order.order_text }}){% endif %}
</div>
{% endfor %}

zipline_app/templates/zipline_app/results.html
<h1>{{ order.order_text }}</h1>

Order Details
<ul>
  <li>{{order.asset.asset_symbol}}</li>
  <li>{{order.order_side}}</li>
  <li>{{order.order_qty_unsigned}}</li>
  <li>{{order.pub_date}}</li>
  <li>{{ order.order_text }}</li>
</ul>

Fills
<ul>
{% for fill in order.fill_set.all %}
    <li>
      {{fill.fill_side}},
      {{fill.fill_qty_unsigned}},
      {{fill.fill_price}},
      {{fill.pub_date}},
      {{ fill.dedicated_to_order }},
      {{ fill.fill_text }}
      --
      {{ fill.votes }}
      vote{{ fill.votes|pluralize }}
    </li>
{% endfor %}
</ul>

<a href="{% url 'zipline_app:orders-detail' order.id %}">Vote again?</a>