polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/ordersOnly/
    url(r'^ordersOnly/$', views.OrdersOnlyView.as_view(), name='ordersOnly'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /polls/assets/
    url(r'^assets/$', views.AssetList.as_view(), name='assets-list'),
    # ex: /polls/assets/new/
    url(r'^assets/new/$', views.AssetCreate.as_view(), name='assets-new'),
    # ex: /polls/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', views.AssetDelete.as_view(), name='assets-delete'),

]

zipline/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

zipline_app/urls.py
from django.conf.urls import url

from .views.zipline_app import zipline_app as views
from .views.zipline_app import blotter
from .views.zipline_app import order, asset, fill, account, autocomplete
from django.contrib.auth import views as auth_views

app_name='zipline_app'
urlpatterns = [
    # ex: /<root>/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /<root>/blotter/sideBySide
    url(r'^blotter/sideBySide/$', blotter.BlotterSideBySideView.as_view(), name='blotter-sideBySide'),
    # ex: /<root>/blotter/engine/
    url(r'^blotter/engine/$', blotter.BlotterEngineView.as_view(), name='blotter-engine'),
    # ex: /<root>/blotter/concealed/
    url(r'^blotter/concealed/$', blotter.BlotterConcealedView.as_view(), name='blotter-concealed'),
    # ex: /<root>/blotter/download/
    url(r'^blotter/download/$', blotter.BlotterDownloadView.as_view(), name='blotter-download'),

    # ex: /<root>/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /<root>/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /<root>/accounts/
    url(r'^accounts/$', account.AccountList.as_view(), name='accounts-list'),
    # ex: /<root>/accounts/new/
    url(r'^accounts/new/$', account.AccountCreate.as_view(), name='accounts-new'),
    # ex: /<root>/accounts/5/
    url(r'^accounts/(?P<pk>[0-9]+)/$', account.AccountDetailView.as_view(), name='accounts-detail'),
    # ex: /<root>/accounts/1/update/
    url(r'^accounts/(?P<pk>[0-9]+)/update/$', account.AccountUpdateView.as_view(), name='accounts-update'),
    # ex: /<root>/accounts/1/delete/
    url(r'^accounts/(?P<pk>[0-9]+)/delete/$', account.AccountDelete.as_view(), name='accounts-delete'),

    # ex: /<root>/assets/
    url(r'^assets/$', asset.AssetList.as_view(), name='assets-list'),
    # ex: /<root>/assets/new/
    url(r'^assets/new/$', asset.AssetCreate.as_view(), name='assets-new'),
    # ex: /<root>/assets/5/
    url(r'^assets/(?P<pk>[0-9]+)/$', asset.AssetDetailView.as_view(), name='assets-detail'),
    # ex: /<root>/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', asset.AssetDelete.as_view(), name='assets-delete'),
    # ex: /<root>/assets/1/update/
    url(r'^assets/(?P<pk>[0-9]+)/update/$', asset.AssetUpdateView.as_view(), name='assets-update'),

    # ex: /<root>/fills/
    url(r'^fills/$', fill.FillList.as_view(), name='fills-list'),
    # ex: /<root>/fills/5/
    url(r'^fills/(?P<pk>[0-9]+)/$', fill.FillDetailView.as_view(), name='fills-detail'),
    # ex: /<root>/fills/new/
    url(r'^fills/new/$', fill.FillCreate.as_view(), name='fills-new'),
    # ex: /<root>/fills/1/update/
    url(r'^fills/(?P<pk>[0-9]+)/update/$', fill.FillUpdateView.as_view(), name='fills-update'),
    # ex: /<root>/fills/1/delete/
    url(r'^fills/(?P<pk>[0-9]+)/delete/$', fill.FillDelete.as_view(), name='fills-delete'),

    # ex: /<root>/orders/
    url(r'^orders/$', order.OrderList.as_view(), name='orders-list'),
    # ex: /<root>/orders/5/
    url(r'^orders/(?P<pk>[0-9]+)/$', order.OrderDetailView.as_view(), name='orders-detail'),
    # ex: /<root>/orders/new/
    url(r'^orders/new/$', order.OrderCreate.as_view(), name='orders-new'),
    # ex: /<root>/orders/1/delete/
    url(r'^orders/(?P<pk>[0-9]+)/delete/$', order.OrderDelete.as_view(), name='orders-delete'),
    # ex: /<root>/orders/5/update/
    url(r'^orders/(?P<pk>[0-9]+)/update/$', order.OrderUpdateView.as_view(), name='orders-update'),

    # Autocomplete Input Field In Django Template with Jquery-UI
    # http://blog.appliedinformaticsinc.com/autocomplete-input-field-in-django-template-with-jquery-ui/
    url(r'^autocomplete/asset/$',   autocomplete.AutoCompleteAssetView.as_view(),   name='autocomplete-asset'),
    url(r'^autocomplete/account/$', autocomplete.AutoCompleteAccountView.as_view(), name='autocomplete-account'),

    # user login
    # https://docs.djangoproject.com/en/1.10/topics/auth/default/#the-login-required-decorator
    url(r'^users/login/$', auth_views.login, name='login'),
    url(r'^users/logout/$', auth_views.logout, name='logout'),
]

zipline_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('zipline_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
]

zipline_app/forms.py
from .models.zipline_app.fill import Fill
from .models.zipline_app.order import Order
from .widgets import AssetModelSelect2Widget, AccountModelSelect2Widget
from django import forms

# override widget in createview
# http://stackoverflow.com/a/21407374/4126114
# Override a Django generic class-based view widget
# http://stackoverflow.com/a/27322032/4126114
class FillForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Fill
    fields = [
      'pub_date', 'asset', 'fill_side', 'fill_qty_unsigned', 'fill_price', 'fill_text', 'tt_order_key',
      'dedicated_to_order'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget()
    }

class OrderForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Order
    fields = [
      'pub_date', 'asset', 'order_side', 'order_qty_unsigned', 'account', 'order_text',
      'order_type', 'limit_price', 'order_validity', 'validity_date'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget(),
      'account': AccountModelSelect2Widget(),
    }

zipline_app/views.py
#from django.shortcuts import render
# Create your views here.

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models.zipline_app.zipline_app import Order, Fill, ZlModel, Asset

from django.utils import timezone

from django.contrib import messages
from pandas import Timedelta
from numpy import concatenate

class OrdersOnlyView(generic.ListView):
    template_name = 'zipline_app/ordersOnly.html'
    context_object_name = 'latest_order_list'

    def get_queryset(self):
        """Return the last five published orders."""
        if any(ZlModel.zl_unused):
          #print("add to messages")
          messages.add_message(self.request, messages.ERROR, "You have unused fills.")

        return Order.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')#[:5]

    # Can I have multiple lists in a Django generic.ListView?
    # http://stackoverflow.com/a/18813102/4126114
    def get_context_data(self, *args, **kwargs):
        context = super(OrdersOnlyView, self).get_context_data(*args, **kwargs)
        """Return the last five published fills."""
        context['latest_fill_list'] = Fill.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')#[:5]

        # get matching engine model
        context["zl_open"]=ZlModel.zl_open
        context["zl_closed"]=ZlModel.zl_closed
        context["zl_txns"]=ZlModel.zl_txns
        context["zl_open_keyed"]=ZlModel.zl_open_keyed
        context["zl_unused"] = ZlModel.zl_unused.items()

        return context

class AssetCreate(generic.CreateView):
  model = Asset
  fields = ['asset_symbol','asset_name','asset_exchange']

# inheriting from create+get_context with asset_list instead of inheriting from listview
# so that I can have the inline in create
# http://stackoverflow.com/a/12883683/4126114
class AssetList(AssetCreate):
  template_name = 'zipline_app/asset_list.html'
  def get_context_data(self, *args, **kwargs):
    context = super(AssetList, self).get_context_data(*args, **kwargs)
    context["asset_list"] = Asset.objects.all()
    return context

class AssetDelete(generic.DeleteView):
    model = Asset
    success_url = reverse_lazy('zipline_app:assets-list')

class IndexView(generic.ListView):
    template_name = 'zipline_app/index.html'
    context_object_name = 'combined'

    def get_queryset(self):
        combined = []
        for minute in sorted(ZlModel.all_minutes, reverse=True):
          minuteP1 = minute + Timedelta(minutes=1)
          orders = Order.objects.filter(
            pub_date__gte=minute,
            pub_date__lt =minuteP1
          )
          fills = Fill.objects.filter(
            pub_date__gte=minute,
            pub_date__lt =minuteP1,
          )
          sids_orders = [o.asset.id for o in orders]
          sids_fills  = [f.asset.id for f in fills]
          sids = concatenate((sids_orders,sids_fills))
          sids = sorted(list(set(sids)))
          duos=[]
          for sid in sids:
            asset = Asset.objects.get(id=sid)
            asset_fills = fills.filter(asset=asset)
            asset_orders = orders.filter(asset=asset)
            duos.append({
              "asset": asset,
              "colspan": max(len(asset_orders),len(asset_fills)),
              "orders": asset_orders,
              "fills": asset_fills
            })

          combined.append({
            "minute":minute,
            "duos":duos
          })
        return combined

class DetailView(generic.DetailView):
    model = Order
    template_name = 'zipline_app/detail.html'
    def get_queryset(self):
        """
        Excludes any orders that aren't published yet.
        """
        return Order.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Order
    template_name = 'zipline_app/results.html'

def vote(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    try:
        selected_fill = order.fill_set.get(pk=request.POST['fill'])
    except (KeyError, Fill.DoesNotExist):
        # Redisplay the order voting form.
        return render(request, 'zipline_app/detail.html', {
            'order': order,
            'error_message': "You didn't select a fill.",
        })
    else:
        selected_fill.votes += 1
        selected_fill.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('zipline_app:results', args=(order.id,)))

zipline_app/templates/zipline_app/blotter/_create_modals.html
{# Load the tag library #}
{% load bootstrap3 %}

<!--
     Button trigger modal from
     http://getbootstrap.com/javascript/#live-demo
-->

<!-- Modal -->
<div class="modal fade" id="accounts-new" tabindex="-1" role="dialog" aria-labelledby="accounts-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      {# {% include "zipline_app/account/_account_form.html" %} #}
      <form action="{% url 'zipline_app:accounts-new' %}" method="post" class="form">
        {% csrf_token %}
        <!-- hidden form field -->
        <input type="hidden" name="source" value="{{source}}">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="accounts-new-label">New account</h4>
        </div>

        <div class="modal-body">
          {% bootstrap_form account_form layout='horizontal' %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="assets-new" tabindex="-1" role="dialog" aria-labelledby="assets-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      {# {% include "zipline_app/asset/_asset_form_bootstrap_vanilla.html" %} #}
      <form action="{% url 'zipline_app:assets-new' %}" method="post" class="form">
        {% csrf_token %}
        <!-- hidden form field -->
        <input type="hidden" name="source" value="{{source}}">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="assets-new-label">New asset</h4>
        </div>

        <div class="modal-body">
          {% bootstrap_form asset_form layout='horizontal' %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

{% include 'zipline_app/blotter/_create_modals_order.html' %}

{% include 'zipline_app/blotter/_create_modals_fill.html' %}

{% include 'zipline_app/blotter/_create_modals_js.html' %}

zipline_app/templates/zipline_app/blotter/_create_modals_account.html
{# Load the tag library #}
{% load bootstrap3 %}

<!-- Modal -->
<div class="modal fade" id="accounts-new" tabindex="-1" role="dialog" aria-labelledby="accounts-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <form action="{% url 'zipline_app:accounts-new' %}" method="post" class="form">
        {% csrf_token %}
        <!-- hidden form field -->
        <input type="hidden" name="source" value="{{source}}">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="accounts-new-label">New account</h4>
        </div>

        <div class="modal-body">
          {% bootstrap_form account_form layout='horizontal' %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

zipline_app/templates/zipline_app/blotter/_create_modals_fill.html
{# Load the tag library #}
{% load bootstrap3 %}

{# copied from https://github.com/applegrew/django-select2/blob/master/tests/testapp/templates/form.html#L5 #}
{{ fill_form.media.css }}

<!-- Modal: do not use tabindex=-1
    http://stackoverflow.com/a/18487440/4126114
-->
<div class="modal fade" id="fills-new" role="dialog" aria-labelledby="fills-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      {% comment %}
        <form action="{% url 'zipline_app:fills-new' %}" method="post">
          {% csrf_token %}
          {{ fill_form.as_p }}
          <input type="hidden" name="source" value="{{source}}">
          <input type="submit" value="Save" />
        </form>
      {% endcomment %}

      {# {% include "zipline_app/asset/_asset_form_bootstrap_vanilla.html" %} #}
      <form action="{% url 'zipline_app:fills-new' %}" method="post" class="form-horizontal">
        {% csrf_token %}

        <!-- hidden form field -->
        <input type="hidden" name="source" value="{{source}}">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="fills-new-label">New fill</h4>
        </div>


        <div class="modal-body">
              {% bootstrap_field field=fill_form.pub_date layout='horizontal' %}
              {% bootstrap_field field=fill_form.asset layout='horizontal' %}
              {% bootstrap_field field=fill_form.fill_side layout='horizontal' %}
              {% bootstrap_field field=fill_form.fill_qty_unsigned layout='horizontal' %}
              {% bootstrap_field field=fill_form.fill_price layout='horizontal' %}
              {% bootstrap_field field=fill_form.tt_order_key layout='horizontal' %}
              {% bootstrap_field field=fill_form.fill_text layout='horizontal' %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

{# copied from https://github.com/applegrew/django-select2/blob/master/tests/testapp/templates/form.html#L24 #}
{{ fill_form.media.js }}

zipline_app/templates/zipline_app/blotter/base.html
{% extends "zipline_app/base.html" %}

{% block content %}
 {% include 'zipline_app/blotter/_create_modals.html' %}
  <div class='row'>
    <div class='pull-right btn-group'>
      <button class='btn btn-default' data-toggle="modal" data-target="#orders-new">
        Order
        <span class="glyphicon glyphicon-plus"></span>
      </button>
      {% if source != 'blotter-concealed' %}
      <button class='btn btn-default' href="#" data-toggle="modal" data-target="#fills-new">
        Fill
        <span class="glyphicon glyphicon-plus"></span>
      </button>
      {% endif %}
      <div class="btn-group" role="group" aria-label="view">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          View
          <span class="glyphicon glyphicon-list"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right">
          <li>
            <a href="{% url 'zipline_app:blotter-sideBySide' %}">Side-by-side</a>
          </li>
          <li>
            <a href="{% url 'zipline_app:blotter-engine' %}">Engine</a>
          </li>
          <li>
            <a href="{% url 'zipline_app:blotter-concealed' %}">Concealed</a>
          </li>
        </ul>
      </div>
      <a class="btn btn-default" href="{% url 'zipline_app:blotter-download' %}">Download</a>
    </div>
  </div>

  <div style="margin-top:5px;margin-bottom:5px"></div>

  <div>
      {% block content_blotter %}
      {% endblock %}
  </div>
{% endblock %}

zipline_app/templates/zipline_app/blotter/concealed.html
{% extends "zipline_app/blotter/base.html" %}
{% load humanize %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content_blotter %}

  {% include 'zipline_app/blotter/sideBySide/_extras.html' %}

  <div>

    <em>
      <div class="row">
        <div class="col-xs-1"><!-- timestamp --></div>
        <div class="col-xs-10">
          <div class="row">
            <div class="col-xs-7">
              <div class="row">
                <div class="col-xs-2"><!-- asset --></div>
                <div class="col-xs-10 text-left"><b>Orders</b></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </em>

    <em>
      <div class="row">
        <div class="col-xs-1"><!-- timestamp --></div>
        <div class="col-xs-10">
          <div class="row">
            <div class="col-xs-7">
              <div class="row">
                <div class="col-xs-2"><b>Asset</b></div>
                <div class="col-xs-10">
                  <div class="row">
                    <div class="col-xs-2">Account</div>
                    <div class="col-xs-2 text-right"><abbr title="Quantity">Q</abbr></div>
                    <div class="col-xs-2 text-right"><abbr title="Filled">F</abbr></div>
                    <div class="col-xs-2 text-right"><abbr title="Average Price">P</abbr></div>
                    <div class="col-xs-4"></div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="col-xs-1"><!-- timestamp --></div>
      </div>
    </em>

    {% for minute in combined %}
    <hr style="margin-top:5px;margin-bottom:5px">

    {# https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#ifchanged #}
    {% ifchanged minute.minute.date %}
      <div class="row text-center text-info">
        <br>&nbsp;
        {# {{ minute.minute.date }} #}
        {{minute.minute|date:"Y-m-d"}}
        <br>&nbsp;
      </div>
    {% endifchanged %}

    <div class="row">
        <div class="col-xs-1 text-right">
          <em>
            <div class="row"><b>{{minute.minute|date:"H:i"}}</b></div>
            {#<div class="row small text-muted">{{minute.minute|date:"Y-m-d"}}</div>#}
          </em>
        </div>

        <div class="col-xs-10">
          {% for duo in minute.duos %}
          <div class="row">
            <div class="col-xs-7">
              <div class="row">
                <div class="col-xs-2" title="{{duo.asset}}">
                  {% if duo.orders|length > 0 %}
                  <a href="{% url 'zipline_app:assets-detail' duo.asset.id %}">
                    {{duo.asset.asset_symbol}}
                  </a>
                  {% endif %}
                </div>

                <div class="col-xs-10">
                  {% include 'zipline_app/blotter/sideBySide/_orders.html' %}
                </div>
              </div>
            </div>

            <div class="col-xs-5">
            {# re-iterate over orders to show the dedicated fills #}
            {% for order in duo.orders %}
              <div class='row'>
              {% if order.dedicated_fill is not None %}
              Filled by
              <a href="{% url 'zipline_app:fills-detail' order.dedicated_fill.id %}">
                #{{order.dedicated_fill.id}}
              </a>
              ({{order.dedicated_fill.user.username}})
              {% endif %}
              </div>
            {% endfor %}
            </div>

          </div>
          {% endfor %}
        </div>

    </div>
    {% empty %}
      No orders are available.
    {% endfor %}

  </div>

{% endblock %}

zipline_app/templates/zipline_app/blotter/engine.html
{% extends "zipline_app/blotter/base.html" %}
{% load humanize %}

{% block content_blotter %}
{% if latest_order_list %}
    <table class="table">
      <caption>Orders</caption>
      <thead>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>Asset</th>
        <th>Filled</th>
        <th>Side</th>
        <th>Amount</th>
        <th>Account</th>
        <th>Price</th>
        <th>Comment</th>
        <th>&nbsp;</th>
      </thead>
      {% for order in latest_order_list %}
        <tr>
          <td width=" 5%">&nbsp;&nbsp;&nbsp;</td>
          <td width="10%" nowrap>{{order.pub_date}}</td>
          <td width="10%">{{order.asset.asset_symbol}}</td>
          <td width="10%"><font color="red">{{order.filled|intcomma}}</font></td>
          <td width=" 5%">{{order.order_side}}</td>
          <td width="10%">{{order.order_qty_unsigned|intcomma}}</td>
          <td width="10%">{{order.account.account_symbol}}</td>
          <td width="10%"><font color="red">{{order.avgPrice|floatformat:"2"|intcomma}}</font></td>
          <td width="10%" nowrap>{{ order.order_text }}</td>
          <td width="10%"><a href="{% url 'zipline_app:orders-detail' order.id %}">Details</a></td>
        </tr>
      {% endfor %}
    </table>
{% else %}
    <p>No orders are available.</p>
{% endif %}

<br>

{% if latest_fill_list %}
  <table class="table">
    <caption>Fills</caption>
    <thead>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>Asset</th>
      <th>Side</th>
      <th>Qty</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>Price</th>
      <th>Comment</th>
      <th>&nbsp;</th>
    </thead>
    {% for fill in latest_fill_list %}
      <tr>
        <td width="10%">
          {% if fill.has_unused %}
            <font color="red">!!!</font>
          {% endif %}
        </td>
        <td width="10%" nowrap>{{fill.pub_date}}</td>
        <td width="10%">{{fill.asset.asset_symbol}}</td>
        <td width=" 5%">{{fill.fill_side}}</td>
        <td width="10%">{{fill.fill_qty_unsigned}}</td>
        <td width=" 5%">&nbsp;</td>
        <td width="10%">&nbsp;</td>
        <td width="10%">{{fill.fill_price}}</td>
        <td width="10%" nowrap>{{ fill.fill_text }}</td>
        <td width="10%"><a href="{% url 'zipline_app:fills-detail' fill.id %}">Details</a></td>
      </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No fills are available.</p>
{% endif %}

<br>

{% if zl_unused|length > 0 %}
  Assets with extra fills:
  <ul>
  {% for asset,qty in zl_unused %}
    <li>{{asset.symbol}}: {{qty}}</li>
  {% endfor %}
  </ul>
{% endif %}
<br>

<font color="gray">
<table border=1>
<caption>Matching engine</caption>
<tr>
<td>
{% if zl_open|length > 0 %}
    Open orders
    <ul>
    {% for order in zl_open %}
        <li>
            {{order.dt}}:
            {{order.sid.symbol}},
            filled {{order.filled}} / {{order.amount|intcomma}},
            {{order.id}}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No open orders are available.</p>
{% endif %}
</td>

<td>
{% if zl_txns|length > 0 %}
    Transactions
    <ul>
    {% for fill in zl_txns %}
        <li>
          {{fill.dt}}:
          {{fill.sid.symbol}},
          {{fill.amount|intcomma}},
          {{fill.price|intcomma}}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No closed orders are available.</p>
{% endif %}
</td>

<td>
{% if zl_closed|length > 0 %}
    Closed orders
    <ul>
    {% for fill in zl_closed %}
        <li>
          {{fill.dt}}:
          {{fill.sid.symbol}},
          {{fill.amount|intcomma}},
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No closed orders are available.</p>
{% endif %}
</td>
</tr>
</table>
</font>

{% endblock %}