polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/ordersOnly/
    url(r'^ordersOnly/$', views.OrdersOnlyView.as_view(), name='ordersOnly'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /polls/assets/
    url(r'^assets/$', views.AssetList.as_view(), name='assets-list'),
    # ex: /polls/assets/new/
    url(r'^assets/new/$', views.AssetCreate.as_view(), name='assets-new'),
    # ex: /polls/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', views.AssetDelete.as_view(), name='assets-delete'),

]

zipline/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

zipline_app/urls.py
from django.conf.urls import url

from .views.zipline_app import zipline_app as views
from .views.zipline_app import blotter
from .views.zipline_app import order, asset, fill, account, autocomplete
from django.contrib.auth import views as auth_views

app_name='zipline_app'
urlpatterns = [
    # ex: /<root>/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /<root>/blotter/sideBySide
    url(r'^blotter/sideBySide/$', blotter.BlotterSideBySideView.as_view(), name='blotter-sideBySide'),
    # ex: /<root>/blotter/engine/
    url(r'^blotter/engine/$', blotter.BlotterEngineView.as_view(), name='blotter-engine'),
    # ex: /<root>/blotter/concealed/
    url(r'^blotter/concealed/$', blotter.BlotterConcealedView.as_view(), name='blotter-concealed'),
    # ex: /<root>/blotter/download/
    url(r'^blotter/download/$', blotter.BlotterDownloadView.as_view(), name='blotter-download'),

    # ex: /<root>/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /<root>/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /<root>/accounts/
    url(r'^accounts/$', account.AccountList.as_view(), name='accounts-list'),
    # ex: /<root>/accounts/new/
    url(r'^accounts/new/$', account.AccountCreate.as_view(), name='accounts-new'),
    # ex: /<root>/accounts/5/
    url(r'^accounts/(?P<pk>[0-9]+)/$', account.AccountDetailView.as_view(), name='accounts-detail'),
    # ex: /<root>/accounts/1/update/
    url(r'^accounts/(?P<pk>[0-9]+)/update/$', account.AccountUpdateView.as_view(), name='accounts-update'),
    # ex: /<root>/accounts/1/delete/
    url(r'^accounts/(?P<pk>[0-9]+)/delete/$', account.AccountDelete.as_view(), name='accounts-delete'),

    # ex: /<root>/assets/
    url(r'^assets/$', asset.AssetList.as_view(), name='assets-list'),
    # ex: /<root>/assets/new/
    url(r'^assets/new/$', asset.AssetCreate.as_view(), name='assets-new'),
    # ex: /<root>/assets/5/
    url(r'^assets/(?P<pk>[0-9]+)/$', asset.AssetDetailView.as_view(), name='assets-detail'),
    # ex: /<root>/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', asset.AssetDelete.as_view(), name='assets-delete'),
    # ex: /<root>/assets/1/update/
    url(r'^assets/(?P<pk>[0-9]+)/update/$', asset.AssetUpdateView.as_view(), name='assets-update'),

    # ex: /<root>/fills/
    url(r'^fills/$', fill.FillList.as_view(), name='fills-list'),
    # ex: /<root>/fills/5/
    url(r'^fills/(?P<pk>[0-9]+)/$', fill.FillDetailView.as_view(), name='fills-detail'),
    # ex: /<root>/fills/new/
    url(r'^fills/new/$', fill.FillCreate.as_view(), name='fills-new'),
    # ex: /<root>/fills/1/update/
    url(r'^fills/(?P<pk>[0-9]+)/update/$', fill.FillUpdateView.as_view(), name='fills-update'),
    # ex: /<root>/fills/1/delete/
    url(r'^fills/(?P<pk>[0-9]+)/delete/$', fill.FillDelete.as_view(), name='fills-delete'),

    # ex: /<root>/orders/
    url(r'^orders/$', order.OrderList.as_view(), name='orders-list'),
    # ex: /<root>/orders/5/
    url(r'^orders/(?P<pk>[0-9]+)/$', order.OrderDetailView.as_view(), name='orders-detail'),
    # ex: /<root>/orders/new/
    url(r'^orders/new/$', order.OrderCreate.as_view(), name='orders-new'),
    # ex: /<root>/orders/1/delete/
    url(r'^orders/(?P<pk>[0-9]+)/delete/$', order.OrderDelete.as_view(), name='orders-delete'),
    # ex: /<root>/orders/5/update/
    url(r'^orders/(?P<pk>[0-9]+)/update/$', order.OrderUpdateView.as_view(), name='orders-update'),

    # Autocomplete Input Field In Django Template with Jquery-UI
    # http://blog.appliedinformaticsinc.com/autocomplete-input-field-in-django-template-with-jquery-ui/
    url(r'^autocomplete/asset/$',   autocomplete.AutoCompleteAssetView.as_view(),   name='autocomplete-asset'),
    url(r'^autocomplete/account/$', autocomplete.AutoCompleteAccountView.as_view(), name='autocomplete-account'),

    # user login
    # https://docs.djangoproject.com/en/1.10/topics/auth/default/#the-login-required-decorator
    url(r'^users/login/$', auth_views.login, name='login'),
    url(r'^users/logout/$', auth_views.logout, name='logout'),
]

zipline_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('zipline_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
]

zipline_app/forms.py
from .models.zipline_app.fill import Fill
from .models.zipline_app.order import Order
from .widgets import AssetModelSelect2Widget, AccountModelSelect2Widget
from django import forms

# override widget in createview
# http://stackoverflow.com/a/21407374/4126114
# Override a Django generic class-based view widget
# http://stackoverflow.com/a/27322032/4126114
class FillForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Fill
    fields = [
      'pub_date', 'asset', 'fill_side', 'fill_qty_unsigned', 'fill_price', 'fill_text', 'tt_order_key',
      'dedicated_to_order'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget()
    }

class OrderForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Order
    fields = [
      'pub_date', 'asset', 'order_side', 'order_qty_unsigned', 'account', 'order_text',
      'order_type', 'limit_price', 'order_validity', 'validity_date'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget(),
      'account': AccountModelSelect2Widget(),
    }

zipline_app/views.py
#from django.shortcuts import render
# Create your views here.

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models.zipline_app.zipline_app import Order, Fill, ZlModel, Asset

from django.utils import timezone

from django.contrib import messages
from pandas import Timedelta
from numpy import concatenate

class OrdersOnlyView(generic.ListView):
    template_name = 'zipline_app/ordersOnly.html'
    context_object_name = 'latest_order_list'

    def get_queryset(self):
        """Return the last five published orders."""
        if any(ZlModel.zl_unused):
          #print("add to messages")
          messages.add_message(self.request, messages.ERROR, "You have unused fills.")

        return Order.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')#[:5]

    # Can I have multiple lists in a Django generic.ListView?
    # http://stackoverflow.com/a/18813102/4126114
    def get_context_data(self, *args, **kwargs):
        context = super(OrdersOnlyView, self).get_context_data(*args, **kwargs)
        """Return the last five published fills."""
        context['latest_fill_list'] = Fill.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')#[:5]

        # get matching engine model
        context["zl_open"]=ZlModel.zl_open
        context["zl_closed"]=ZlModel.zl_closed
        context["zl_txns"]=ZlModel.zl_txns
        context["zl_open_keyed"]=ZlModel.zl_open_keyed
        context["zl_unused"] = ZlModel.zl_unused.items()

        return context

class AssetCreate(generic.CreateView):
  model = Asset
  fields = ['asset_symbol','asset_name','asset_exchange']

# inheriting from create+get_context with asset_list instead of inheriting from listview
# so that I can have the inline in create
# http://stackoverflow.com/a/12883683/4126114
class AssetList(AssetCreate):
  template_name = 'zipline_app/asset_list.html'
  def get_context_data(self, *args, **kwargs):
    context = super(AssetList, self).get_context_data(*args, **kwargs)
    context["asset_list"] = Asset.objects.all()
    return context

class AssetDelete(generic.DeleteView):
    model = Asset
    success_url = reverse_lazy('zipline_app:assets-list')

class IndexView(generic.ListView):
    template_name = 'zipline_app/index.html'
    context_object_name = 'combined'

    def get_queryset(self):
        combined = []
        for minute in sorted(ZlModel.all_minutes, reverse=True):
          minuteP1 = minute + Timedelta(minutes=1)
          orders = Order.objects.filter(
            pub_date__gte=minute,
            pub_date__lt =minuteP1
          )
          fills = Fill.objects.filter(
            pub_date__gte=minute,
            pub_date__lt =minuteP1,
          )
          sids_orders = [o.asset.id for o in orders]
          sids_fills  = [f.asset.id for f in fills]
          sids = concatenate((sids_orders,sids_fills))
          sids = sorted(list(set(sids)))
          duos=[]
          for sid in sids:
            asset = Asset.objects.get(id=sid)
            asset_fills = fills.filter(asset=asset)
            asset_orders = orders.filter(asset=asset)
            duos.append({
              "asset": asset,
              "colspan": max(len(asset_orders),len(asset_fills)),
              "orders": asset_orders,
              "fills": asset_fills
            })

          combined.append({
            "minute":minute,
            "duos":duos
          })
        return combined

class DetailView(generic.DetailView):
    model = Order
    template_name = 'zipline_app/detail.html'
    def get_queryset(self):
        """
        Excludes any orders that aren't published yet.
        """
        return Order.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Order
    template_name = 'zipline_app/results.html'

def vote(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    try:
        selected_fill = order.fill_set.get(pk=request.POST['fill'])
    except (KeyError, Fill.DoesNotExist):
        # Redisplay the order voting form.
        return render(request, 'zipline_app/detail.html', {
            'order': order,
            'error_message': "You didn't select a fill.",
        })
    else:
        selected_fill.votes += 1
        selected_fill.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('zipline_app:results', args=(order.id,)))

zipline_app/templates/zipline_app/blotter/sideBySide/_create.html
{# Load the tag library #}
{% load bootstrap3 %}


<!--
     Button trigger modal from
     http://getbootstrap.com/javascript/#live-demo
-->

<!-- Modal -->
<div class="modal fade" id="accounts-new" tabindex="-1" role="dialog" aria-labelledby="accounts-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      {# {% include "zipline_app/account/_account_form.html" %} #}
      <form action="{% url 'zipline_app:accounts-new' %}" method="post" class="form">
        {% csrf_token %}
        <!-- hidden form field -->
        <input type="hidden" name="source" value="combined">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="accounts-new-label">New account</h4>
        </div>

        <div class="modal-body">
          {% bootstrap_form account_form layout='horizontal' %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="assets-new" tabindex="-1" role="dialog" aria-labelledby="assets-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      {# {% include "zipline_app/asset/_asset_form_bootstrap_vanilla.html" %} #}
      <form action="{% url 'zipline_app:assets-new' %}" method="post" class="form">
        {% csrf_token %}
        <!-- hidden form field -->
        <input type="hidden" name="source" value="combined">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="assets-new-label">New asset</h4>
        </div>

        <div class="modal-body">
          {% bootstrap_form asset_form layout='horizontal' %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="orders-new" tabindex="-1" role="dialog" aria-labelledby="orders-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <!--
        <form action="{% url 'zipline_app:orders-new' %}" method="post">
          {% csrf_token %}
          {{ order_form.as_p }}
          <input type="hidden" name="source" value="combined">
          <input type="submit" value="Save" />
        </form>
      -->

      {# {% include "zipline_app/asset/_asset_form_bootstrap_vanilla.html" %} #}
      <form action="{% url 'zipline_app:orders-new' %}" method="post" class="form">
        {% csrf_token %}
        <!-- hidden timestamp -->
        <div style="display: none;">{% bootstrap_field field=order_form.pub_date layout='horizontal' %}</div>

        <!-- hidden form field -->
        <input type="hidden" name="source" value="combined">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="orders-new-label">New order</h4>
        </div>

        <div class="modal-body">
          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=order_form.pub_date layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=order_form.asset layout='horizontal' %}
            </div>
            <div class='col-xs-4'>
              <input class="ac-asset-input" placeholder="Search" />
              <div class="ac-asset-response"></div>
              <div class="ac-asset-status"></div>
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=order_form.account layout='horizontal' %}
            </div>
            <div class='col-xs-4'>
              <input class="ac-account-input" placeholder="Search" />
              <div class="ac-account-response"></div>
              <div class="ac-account-status"></div>
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=order_form.order_side layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=order_form.amount_unsigned layout='horizontal' %}
            </div>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="fills-new" tabindex="-1" role="dialog" aria-labelledby="fills-new-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <!--
        <form action="{% url 'zipline_app:fills-new' %}" method="post">
          {% csrf_token %}
          {{ fill_form.as_p }}
          <input type="hidden" name="source" value="combined">
          <input type="submit" value="Save" />
        </form>
      -->

      {# {% include "zipline_app/asset/_asset_form_bootstrap_vanilla.html" %} #}
      <form action="{% url 'zipline_app:fills-new' %}" method="post" class="form">
        {% csrf_token %}

        <!-- hidden form field -->
        <input type="hidden" name="source" value="combined">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="fills-new-label">New fill</h4>
        </div>

        <div class="modal-body">
          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.pub_date layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.asset layout='horizontal' %}
            </div>
            <div class='col-xs-4'>
              <input class="ac-asset-input form-control" placeholder="Search" />
              <div class="ac-asset-response"></div>
              <div class="ac-asset-status"></div>
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.fill_side layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.fill_qty_unsigned layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.fill_price layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.tt_order_key layout='horizontal' %}
            </div>
          </div>

          <div class='row'>
            <div class='col-xs-8'>
              {% bootstrap_field field=fill_form.fill_text layout='horizontal' %}
            </div>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {% bootstrap_button content="Save" button_type="submit" button_class="btn-primary" %}
        </div>
      </form>

    </div>
  </div>
</div>

<script type="text/javascript">
$(function() {
  <!-- How to reset form body in bootstrap modal box
       http://stackoverflow.com/questions/15827262/ddg#20918538
       -->
  $('.modal').on('hidden.bs.modal', function(){
        $(this).find('form')[0].reset();
        $(this).find('input').prop('disabled',false);
        $(this).find('select').prop('disabled',false);
        $(this).find('hidden.extra-dyn').remove();
  });



  <!-- convert asset/account input to autocomplete from jquery ui -->
  function createAutocomplete(id,name) {
    $(id+" .ac-"+name+"-input").autocomplete({
      source: "/autocomplete/"+name+"/",
      appendTo: $(id+" .ac-"+name+"-response"),
      response: function( event, ui ) {
        if(ui.content.length==0) {
          $(id+" .ac-"+name+"-status").text("No results");
        } else {
          $(id+" .ac-"+name+"-status").text("");
        }
      },
      search: function( event, ui ) {
        $(id+" .ac-"+name+"-status").text("Searching...");
      },
      autoFocus: true,
      select: function( event, ui ) {
        $(id+" form select[name='"+name+"']").val(ui.item.value);
        $(id+" .ac-"+name+"-input").val("");
        event.preventDefault();
      }
    });
  }

  createAutocomplete("#orders-new","account");
  createAutocomplete("#orders-new","asset");
  createAutocomplete("#fills-new","asset");

});
</script>

<!-- ######################################### -->

<div class="row">
  <div class="col-xs-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#accounts-new">
      <span class="glyphicon glyphicon-plus"></span>
      Account
    </button>
  </div>
  <div class="col-xs-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#assets-new">
      <span class="glyphicon glyphicon-plus"></span>
      Asset
    </button>
  </div>
  <div class="col-xs-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#orders-new">
      <span class="glyphicon glyphicon-plus"></span>
      Order
    </button>
  </div>
  <div class="col-xs-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#fills-new">
      <span class="glyphicon glyphicon-plus"></span>
      Fill
    </button>
  </div>
</div>

<div style="margin-top:5px;margin-bottom:5px"></div>

zipline_app/templates/zipline_app/blotter/sideBySide/_fills.html
{% load humanize %}
{% load bootstrap3 %}

{% for fill in duo.fills %}
<div class="row {% if fill.has_unused %}text-danger{% endif %}">
  <div class="col-xs-3 text-primary text-right">
    {{fill.fill_side}}
    {{fill.fill_qty_unsigned}}
  </div>
  <div class="col-xs-3 text-primary text-right">{{fill.fill_price}}</div>
  <div class="col-xs-6">
    <div class="row">

      <div class="col-xs-4">
        {% if fill.has_unused %}
        <abbr title="Asset has unmatched fills">
          <span class="glyphicon glyphicon-alert"></span>
        </abbr>
        {% endif %}
      </div>

      <div class="col-xs-8 text-right">
        <abbr title="Fill">
          <a href="{% url 'zipline_app:fills-detail' fill.id %}">
            #{{fill.id}}
          </a>
        </abbr>
        ({{fill.user.username}})
      </div>

    </div>
  </div>
</div>
{%if fill.fill_text or fill.tt_order_key %}
<div class="row text-muted">
  <div class="col-xs-4 text-left">{{ fill.tt_order_key }}</div>
  <div class="col-xs-8 text-right">{{ fill.fill_text }}</div>
</div>
{% endif %}
{% endfor %}

zipline_app/templates/zipline_app/blotter/sideBySide/_orders.html
{% load humanize %}
{% load bootstrap3 %}

{% for order in duo.orders %}
<div class="row {% if order.filled != order.order_qty_signed %}text-warning{% endif %}">

  <div class="col-xs-2">
    <attr title="{{order.account.account_name}}">
      <a href="{% url 'zipline_app:accounts-detail' order.account.id %}">
        {{order.account.account_symbol}}
      </a>
    </attr>
  </div>

  <div class="col-xs-2 text-right">
    {{order.order_side}}
    {{order.order_qty_unsigned|intcomma}}
  </div>
  <div class="col-xs-2 text-right text-primary">{{order.filled|intcomma}}</div>
  <div class="col-xs-2 text-right text-primary">{{order.avgPrice|floatformat:"2"|intcomma}}</div>

  <div class="col-xs-4">
    <div class="row">
      <div class="col-xs-4">
        {% if order.filled != order.order_qty_signed %}
        <abbr title="Close order #{{order.id}}">
          <button
            type="button"
            class="btn btn-xs fill-from-order"
            data-toggle="modal"
            data-target="#fills-new"
            data-order-id="{{order.id}}"
            data-order-pub_date="{{order.pub_date|date:"Y-m-d H:i:s"}}"
            data-order-order_side="{{order.order_side}}"
            data-order-order_qty_unsigned="{{order.order_qty_unsigned}}"
            data-order-asset-id="{{order.asset.id}}"
            data-order-asset-str="{{order.asset.str}}"
          >
            <span class="glyphicon glyphicon-copy"></span>
          </button>
        </abbr>
        {% endif %}
      </div>

      <div class="col-xs-8">
        <abbr title="Order">
          <a href="{% url 'zipline_app:orders-detail' order.id %}">
            #{{order.id}}
          </a>
        </abbr>
        ({{order.user.username}})
      </div>
    </div>
  </div>
</div>

{% if order.order_text %}
  <div class="row">
    <div class="col-xs-12 text-muted text-left">{{ order.order_text }}</div>
  </div>
{% endif %}
{% endfor %}

<script type="text/javascript">
$(function() {
  $('.fill-from-order').unbind().click(function(){
      // get all data-... attributes
      var data = {
        'order-id': $(this).attr('data-order-id'),
        'pub_date': $(this).attr('data-order-pub_date'),
        'order_side': $(this).attr('data-order-order_side'),
        'order_qty_unsigned': $(this).attr('data-order-order_qty_unsigned'),
        'asset-id': $(this).attr('data-order-asset-id'),
        'asset-str': $(this).attr('data-order-asset-str'),
      };

      // set the default values to the data-... attributes above
      $('#fills-new input[name="pub_date"]').val(data['pub_date']);
      $('#fills-new select[name="fill_side"]').val(data['order_side']);
      $('#fills-new input[name="fill_qty_unsigned"]').val(data['order_qty_unsigned']);

      $newOption = $("<option class='extra-dyn'></option>").val(data['asset-id']).text(data['asset-str']);
      $('#fills-new select[name="asset"]').append($newOption).trigger('change');

      // set to disabled to disallow user from changing
      // note that 'readonly' does not work for select
      $('#fills-new input[name="pub_date"]').prop('disabled', true);
      $('#fills-new select[name="fill_side"]').prop('disabled', true);
      $('#fills-new input[name="fill_qty_unsigned"]').prop('disabled', true);
      $('#fills-new select[name="asset"]').prop('disabled', true);

      // since disabled fields do not get posted, add hidden fields
      // http://stackoverflow.com/a/2834115/4126114
      form=$('#fills-new').find('form');
      $('<input/>', {type:'hidden', class:'extra-dyn', name:'pub_date',          value:data['pub_date']       }).appendTo(form);
      $('<input/>', {type:'hidden', class:'extra-dyn', name:'fill_side',         value:data['order_side']     }).appendTo(form);
      $('<input/>', {type:'hidden', class:'extra-dyn', name:'fill_qty_unsigned', value:data['order_qty_unsigned']}).appendTo(form);
      $('<input/>', {type:'hidden', class:'extra-dyn', name:'asset',             value:data['asset-id']       }).appendTo(form);

      // dedicated to order is a hidden field
      $('<input/>', {type:'hidden', class:'extra-dyn', name:'dedicated_to_order',value:data['order-id']       }).appendTo(form);
  });
});
</script>