polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/ordersOnly/
    url(r'^ordersOnly/$', views.OrdersOnlyView.as_view(), name='ordersOnly'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /polls/assets/
    url(r'^assets/$', views.AssetList.as_view(), name='assets-list'),
    # ex: /polls/assets/new/
    url(r'^assets/new/$', views.AssetCreate.as_view(), name='assets-new'),
    # ex: /polls/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', views.AssetDelete.as_view(), name='assets-delete'),

]

zipline/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

zipline_app/urls.py
from django.conf.urls import url

from .views.zipline_app import zipline_app as views
from .views.zipline_app import blotter
from .views.zipline_app import order, asset, fill, account, autocomplete
from django.contrib.auth import views as auth_views

app_name='zipline_app'
urlpatterns = [
    # ex: /<root>/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /<root>/blotter/sideBySide
    url(r'^blotter/sideBySide/$', blotter.BlotterSideBySideView.as_view(), name='blotter-sideBySide'),
    # ex: /<root>/blotter/engine/
    url(r'^blotter/engine/$', blotter.BlotterEngineView.as_view(), name='blotter-engine'),
    # ex: /<root>/blotter/concealed/
    url(r'^blotter/concealed/$', blotter.BlotterConcealedView.as_view(), name='blotter-concealed'),
    # ex: /<root>/blotter/download/
    url(r'^blotter/download/$', blotter.BlotterDownloadView.as_view(), name='blotter-download'),

    # ex: /<root>/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /<root>/5/vote/
    url(r'^(?P<order_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # ex: /<root>/accounts/
    url(r'^accounts/$', account.AccountList.as_view(), name='accounts-list'),
    # ex: /<root>/accounts/new/
    url(r'^accounts/new/$', account.AccountCreate.as_view(), name='accounts-new'),
    # ex: /<root>/accounts/5/
    url(r'^accounts/(?P<pk>[0-9]+)/$', account.AccountDetailView.as_view(), name='accounts-detail'),
    # ex: /<root>/accounts/1/update/
    url(r'^accounts/(?P<pk>[0-9]+)/update/$', account.AccountUpdateView.as_view(), name='accounts-update'),
    # ex: /<root>/accounts/1/delete/
    url(r'^accounts/(?P<pk>[0-9]+)/delete/$', account.AccountDelete.as_view(), name='accounts-delete'),

    # ex: /<root>/assets/
    url(r'^assets/$', asset.AssetList.as_view(), name='assets-list'),
    # ex: /<root>/assets/new/
    url(r'^assets/new/$', asset.AssetCreate.as_view(), name='assets-new'),
    # ex: /<root>/assets/5/
    url(r'^assets/(?P<pk>[0-9]+)/$', asset.AssetDetailView.as_view(), name='assets-detail'),
    # ex: /<root>/assets/1/delete/
    url(r'^assets/(?P<pk>[0-9]+)/delete/$', asset.AssetDelete.as_view(), name='assets-delete'),
    # ex: /<root>/assets/1/update/
    url(r'^assets/(?P<pk>[0-9]+)/update/$', asset.AssetUpdateView.as_view(), name='assets-update'),

    # ex: /<root>/fills/
    url(r'^fills/$', fill.FillList.as_view(), name='fills-list'),
    # ex: /<root>/fills/5/
    url(r'^fills/(?P<pk>[0-9]+)/$', fill.FillDetailView.as_view(), name='fills-detail'),
    # ex: /<root>/fills/new/
    url(r'^fills/new/$', fill.FillCreate.as_view(), name='fills-new'),
    # ex: /<root>/fills/1/update/
    url(r'^fills/(?P<pk>[0-9]+)/update/$', fill.FillUpdateView.as_view(), name='fills-update'),
    # ex: /<root>/fills/1/delete/
    url(r'^fills/(?P<pk>[0-9]+)/delete/$', fill.FillDelete.as_view(), name='fills-delete'),

    # ex: /<root>/orders/
    url(r'^orders/$', order.OrderList.as_view(), name='orders-list'),
    # ex: /<root>/orders/5/
    url(r'^orders/(?P<pk>[0-9]+)/$', order.OrderDetailView.as_view(), name='orders-detail'),
    # ex: /<root>/orders/new/
    url(r'^orders/new/$', order.OrderCreate.as_view(), name='orders-new'),
    # ex: /<root>/orders/1/delete/
    url(r'^orders/(?P<pk>[0-9]+)/delete/$', order.OrderDelete.as_view(), name='orders-delete'),
    # ex: /<root>/orders/5/update/
    url(r'^orders/(?P<pk>[0-9]+)/update/$', order.OrderUpdateView.as_view(), name='orders-update'),

    # Autocomplete Input Field In Django Template with Jquery-UI
    # http://blog.appliedinformaticsinc.com/autocomplete-input-field-in-django-template-with-jquery-ui/
    url(r'^autocomplete/asset/$',   autocomplete.AutoCompleteAssetView.as_view(),   name='autocomplete-asset'),
    url(r'^autocomplete/account/$', autocomplete.AutoCompleteAccountView.as_view(), name='autocomplete-account'),

    # user login
    # https://docs.djangoproject.com/en/1.10/topics/auth/default/#the-login-required-decorator
    url(r'^users/login/$', auth_views.login, name='login'),
    url(r'^users/logout/$', auth_views.logout, name='logout'),
]

zipline_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('zipline_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
]

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime

from zipline.finance.execution import (
    LimitOrder,
    MarketOrder,
    StopLimitOrder,
    StopOrder,
)

from .matcher import factory as mmm_factory, Matcher as mmm_Matcher
import pandas as pd
from six import iteritems
from functools import reduce

import json
import hashlib
from numpy import average, concatenate
from django.db import connection

# Django Logging
# https://docs.djangoproject.com/en/1.10/topics/logging/
import logging
logger = logging.getLogger(__name__)

from django.urls import reverse

# Create your models here.

def md5_wrap(string):
  return hashlib.md5(string.encode('utf-8')).hexdigest()

class Asset(models.Model):
    asset_symbol = models.CharField(max_length=20)
    asset_exchange = models.CharField(max_length=200)
    asset_name = models.CharField(max_length=200)

    def __str__(self):
        return "%s, %s, %s" % (self.asset_symbol, self.asset_exchange, self.asset_name)

    def to_dict(self):
        return {
          "symbol": self.asset_symbol,
          "exchange": self.asset_exchange,
          "name": self.asset_name
        }

    def get_absolute_url(self):
      return reverse('polls:assets-list')
#      return reverse('polls:assets-list', kwargs={'pk': self.pk})


class Account(models.Model):
    account_symbol = models.CharField(max_length=20)
    def __str__(self):
      return self.account_symbol
 
class Order(models.Model):
    order_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, null=True)
    amount = models.IntegerField(default=0)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    # static variable

    def __str__(self):
        return "%s, %s (%s, %s)" % (self.asset.asset_symbol, self.amount, self.account.account_symbol, self.order_text)

    def md5(self):
        string = "%s, %s, %s (%s, %s)" % (self.pub_date, self.asset.asset_symbol, self.amount, self.account.account_symbol, self.order_text)
        return md5_wrap(string)

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

    def filled(self):
      if self.id in ZlModel.zl_closed_keyed:
        return self.amount
      if self.id in ZlModel.zl_open_keyed:
        return ZlModel.zl_open_keyed[self.id].filled
      return 0

    def fills(self):
      return [txn for txn in ZlModel.zl_txns if txn["order_id"]==self.id]

    def avgPrice(self):
      if self.filled()==0:
        return float('nan')

      sub = self.fills()
      avg = average(a=[txn["price"] for txn in sub], weights=[txn["amount"] for txn in sub])
      return avg

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Fill(models.Model):
    # 2017-01-12: unlink orders from fills and use zipline engine to perform matching
    # order = models.ForeignKey(Order, on_delete=models.CASCADE)
    fill_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    fill_qty = models.IntegerField(default=0)
    fill_price = models.FloatField(default=0)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "%s, %s, %s (%s)" % (self.asset.asset_symbol, self.fill_qty, self.fill_price, self.fill_text)

    def md5(self):
        string = "%s, %s, %s, %s (%s)" % (self.pub_date, self.asset.asset_symbol, self.fill_qty, self.fill_price, self.fill_text)
        return md5_wrap(string)

    def has_unused(self):
      return self.asset.id in ZlModel.zl_unused

class ZlModel:
    md5 = None
    zl_open       = []
    zl_closed     = []
    zl_txns       = []
    zl_open_keyed = {}
    zl_closed_keyed = {}
    fills={}
    orders={}
    assets={}
    zl_unused = {}

    @staticmethod
    def clear():
      ZlModel.md5 = None
      ZlModel.zl_open       = []
      ZlModel.zl_closed     = []
      ZlModel.zl_txns       = []
      ZlModel.zl_open_keyed = {}
      ZlModel.zl_closed_keyed = {}
      ZlModel.fills={}
      ZlModel.orders={}
      ZlModel.assets={}
      ZlModel.zl_unused = {}

    @staticmethod
    def add_asset(asset: Asset):
      #print("adding asset",asset,asset.id)
      ZlModel.assets[asset.id]=asset.to_dict()

    @staticmethod
    def add_fill(fill: Fill):
      #print("Adding fill: %s" % fill)
      if fill.asset.id not in ZlModel.fills:
        ZlModel.fills[fill.asset.id]={}

      ZlModel.fills[fill.asset.id][fill.id]={
        "close": fill.fill_price,
        "volume": fill.fill_qty,
        "dt": pd.Timestamp(fill.pub_date,tz='utc')
      }

    @staticmethod
    def fills_as_dict_df():
      # Copy keys to a new dictionary (Python)
      # http://stackoverflow.com/a/7369284/4126114
      fills2=dict.fromkeys(ZlModel.fills.keys(),{})

      for sid in ZlModel.fills:
        fills2[sid] = pd.DataFrame({})
        sub = ZlModel.fills[sid].values()
        fills2[sid]["close"]=[y["close"] for y in sub]
        fills2[sid]["volume"]=[y["volume"] for y in sub]
        fills2[sid]["dt"]=[y["dt"] for y in sub]
        fills2[sid]=fills2[sid].set_index("dt")
      return fills2

    @staticmethod
    def add_order(order: Order):
      if order.asset.id not in ZlModel.orders:
        ZlModel.orders[order.asset.id]={}

      ZlModel.orders[order.asset.id][order.id] = {
        "dt": order.pub_date,
        "asset": order.asset.id,
        "amount": order.amount,
        "style": MarketOrder()
      }

    @staticmethod
    def delete_asset(asset: Asset):
      ZlModel.assets.pop(asset.id, None)

    @staticmethod
    def delete_fill(fill: Fill):
      # How to remove a key from a python dictionary
      # http://stackoverflow.com/questions/11277432/ddg#11277439
      ZlModel.fills[fill.asset.id].pop(fill.id, None)
      if not any(ZlModel.fills[fill.asset.id]):
        ZlModel.fills.pop(fill.asset.id, None)

    @staticmethod
    def delete_order(order: Order):
      # How to remove a key from a python dictionary
      # http://stackoverflow.com/questions/11277432/ddg#11277439
      ZlModel.orders.pop(order.id, None)

    @staticmethod
    def db_ready():
      tables = connection.introspection.table_names()
      isready = "polls_fill" in tables
      if not isready:
        logger.debug("db tables not available .. skipping zlmodel init")
      return isready

    @staticmethod
    def init():
      if not ZlModel.db_ready():
        return

      for fill in Fill.objects.all():
        ZlModel.add_fill(fill)
      for order in Order.objects.all():
        ZlModel.add_order(order)
      for asset in Asset.objects.all():
        ZlModel.add_asset(asset)

    @staticmethod
    def update():
      if not ZlModel.db_ready():
        return

      md5 = md5_wrap(json.dumps({
        "fills":[x.md5() for x in Fill.objects.all()],
        "orders":[x.md5() for x in Order.objects.all()],
        "assets":{x.id: x.to_dict() for x in Asset.objects.all()},
      }))

      if ZlModel.md5==md5:
        logger.debug("Model unchanged .. not rerunning engine: "+md5)
        return

      logger.debug("Run matching engine: "+md5)

      matcher = mmm_Matcher()

      all_closed, all_txns, open_orders, ZlModel.zl_unused, ZlModel.all_minutes = mmm_factory(
        matcher,
        ZlModel.fills_as_dict_df(),
        ZlModel.orders,
        ZlModel.assets
      )

      ZlModel.zl_open = reduce(
        lambda a, b: concatenate((a,b)),
        [v for k,v in open_orders.items()],
        list()
      )
      ZlModel.zl_closed = all_closed
      ZlModel.zl_txns = [txn.to_dict() for txn in all_txns]
      ZlModel.zl_open_keyed = {v.id: v for v in ZlModel.zl_open}
      ZlModel.zl_closed_keyed = {v.id: v for v in ZlModel.zl_closed}

      # save md5 at the end to ensure re-run if error occured
      ZlModel.md5=md5


# https://docs.djangoproject.com/en/1.11/topics/signals/#connecting-receiver-functions
#from django.core.signals import request_started
#request_started.connect(ZlModel.update)

# connecting signals
from django.db.backends.signals import connection_created
class SignalProcessor:
  #def post_init(sender, **kwargs):
  #  print("Signal: %s, %s" % ("post_init", sender.__name__))

  def update_if_mine(sender):
    condition = sender.__name__=="Fill" or sender.__name__=="Order" or sender.__name__=="Asset"
    if condition:
      ZlModel.update()

  def post_save(sender, instance, **kwargs):
    #logger.debug("Signal: %s, %s" % ("post_save", sender))
    if sender.__name__=="Fill": ZlModel.add_fill(instance)
    if sender.__name__=="Order": ZlModel.add_order(instance)
    if sender.__name__=="Asset": ZlModel.add_asset(instance)
    SignalProcessor.update_if_mine(sender)

  def post_delete(sender, instance, **kwargs):
    #print("Signal: %s, %s" % ("post_delete", sender))
    if sender.__name__=="Fill": ZlModel.delete_fill(instance)
    if sender.__name__=="Order": ZlModel.delete_order(instance)
    if sender.__name__=="Asset": ZlModel.delete_asset(instance)
    SignalProcessor.update_if_mine(sender)

  def connection_created(sender, **kwargs):
  #  print("Signal: %s, %s" % ("connection_created", sender))
    ZlModel.init()
    ZlModel.update()

senders=("polls.Order", "polls.Fill", "polls.Asset")
for sender in senders:
  #models.signals.post_init.connect(SignalProcessor.post_init, sender=sender)
  models.signals.post_save.connect(SignalProcessor.post_save, sender=sender)
  models.signals.post_delete.connect(SignalProcessor.post_delete, sender=sender)
connection_created.connect(SignalProcessor.connection_created)

zipline_app/forms.py
from .models.zipline_app.fill import Fill
from .models.zipline_app.order import Order
from .widgets import AssetModelSelect2Widget, AccountModelSelect2Widget
from django import forms

# override widget in createview
# http://stackoverflow.com/a/21407374/4126114
# Override a Django generic class-based view widget
# http://stackoverflow.com/a/27322032/4126114
class FillForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Fill
    fields = [
      'pub_date', 'asset', 'fill_side', 'fill_qty_unsigned', 'fill_price', 'fill_text', 'tt_order_key',
      'dedicated_to_order'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget()
    }

class OrderForm(forms.ModelForm):
  source=forms.CharField(required=False, widget = forms.HiddenInput())
  class Meta:
    model=Order
    fields = [
      'pub_date', 'asset', 'order_side', 'order_qty_unsigned', 'account', 'order_text',
      'order_type', 'limit_price', 'order_validity', 'validity_date'
    ]
    widgets = {
      'asset': AssetModelSelect2Widget(),
      'account': AccountModelSelect2Widget(),
    }

zipline_app/templates/zipline_app/order/_order_detail.html
{% load humanize %}
{# note that this template is also used in the email, so probably not a good idea to use bootstrap here? Maybe if needed I'll split this into two files, one for the email and another for the UI #}

<h2>Order Details</h2>
<ul>
  <li>Date: {{order.pub_date}}</li>
  <li>Asset: {{order.asset.asset_symbol}}</li>
  <li>Type: {{order.get_order_type_display}}</li>
  {% if order.order_type == 'L' %}
  <li>Limit price: {{order.limit_price}}</li>
  {% endif %}
  <li>Side: {{order.get_order_side_display}}</li>
  <li>Qty: {{order.order_qty_unsigned|intcomma}}</li>
  <li>Filled: <font color="red">{{order.filled|intcomma}}</font></li>
  <li>Status: {{order.get_order_status_display}}</li>
  <li>Account: {{order.account.account_symbol}}</li>
  <li>
    Dedicated fill:
    {% if order.dedicated_fill is not None %}
    <a href="{% url 'zipline_app:fills-detail' order.dedicated_fill.id %}">
      #{{order.dedicated_fill.id}}
    </a>
    {% else %}
    None
    {% endif %}
  </li>
  <li>User: {{order.user.username}}</li>
  <li>
    Validity: {{order.get_order_validity_display}}
    {% if order.order_validity == 'D' %}
    ({{order.validity_date}})
    {% endif %}
  </li>
  <li>Comment: {% if order.order_text %}{{ order.order_text }}{% else %}None{% endif %}</li>
</ul>

{% if domain %}
<p>
  Published in
  <a href="{{domain}}{% url 'zipline_app:blotter-concealed' %}">blotter</a>
  /
  <a href="{{ domain }}{% url 'zipline_app:orders-detail' order.id %}">order #{{order.id}}</a>
</p>
{% endif %}

zipline_app/templates/zipline_app/order/order_confirm_delete.html
{% extends "zipline_app/base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

zipline_app/templates/zipline_app/order/order_detail.html
{% extends "zipline_app/base.html" %}
{% load humanize %}
{% load bootstrap3 %}

{% block content %}

{% include 'zipline_app/order/_order_detail.html' %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<font color="red">
{% if order.fills|length > 0 %}
    Current fills
    <ul>
    {% for fill in order.fills %}
        <li>
          {{fill.dt}}:
          {{fill.sid.symbol}},
          {{fill.amount|intcomma}},
          {{fill.price|intcomma}}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No fills are available.</p>
{% endif %}
</font>

<!--
Fill
<form action="{% url 'zipline_app:vote' order.id %}" method="post">
{% csrf_token %}
{% for fill in order.fill_set.all %}
    <input type="radio" name="fill" id="fill{{ forloop.counter }}" value="{{ fill.id }}" />
    <label for="fill{{ forloop.counter }}">
       {{fill.fill_side}},
       {{fill.fill_qty_unsigned}},
       {{fill.fill_price}},
       {{ fill.fill_text }}
    </label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
-->

        {% if request.user.is_authenticated and order.user == request.user %}

        <!-- delete with confirmation -->
        <a href="{% url 'zipline_app:orders-delete' order.id %}" class='btn btn-danger'>Delete</a>

        <!-- delete without confirmation
        <form action="{% url 'zipline_app:orders-delete' order.id %}" method="post" class="form">
          {% csrf_token %}
          {% bootstrap_button content="Del" icon="minus" button_type="submit" %}
        </form>
        -->

        <a href="{% url 'zipline_app:orders-update' order.id %}" class='btn btn-default'>Edit</a>

        {% endif %}

{##########################################}
<h2>History</h2>
<ul>
  {% for history in order.history %}
  <li>
    {{history.ed_date}}: {{history}}
  </li>
  {% empty %}
  <li>No history</li>
  {% endfor %}
</ul>
{% endblock %}

zipline_app/templates/zipline_app/order/order_form.html
{% extends "zipline_app/base.html" %}

{# Load the tag library #}
{% load bootstrap3 %}

{% block content %}
{{ form.media.css }}

{# it is necessary to keep using order_form (and not replace it with _create_modals_order) because it is the only form that displays errors properly #}
<div class='row'>
<div class='col-md-6'>
<form action="" method="post" class="form" name="main-form">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% comment %}
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-2"><div class="row">{% bootstrap_field field=form.pub_date %}</div></div>
    <div class="col-xs-1"><div class="row">{% bootstrap_field field=form.asset %}</div></div>
    <div class="col-xs-1"><div class="row">{% bootstrap_field field=form.order_side %}</div></div>
    <div class="col-xs-1"><div class="row">{% bootstrap_field field=form.order_qty_unsigned %}</div></div>
    <div class="col-xs-2"><div class="row">{% bootstrap_field field=form.account %}</div></div>
    <div class="col-xs-3"><div class="row">{% bootstrap_field field=form.order_text placeholder="some comments" %}</div></div>
  </div>
  {% endcomment %}
  {% if source %}<input type="hidden" name="source" value="{{source}}" />{% endif %}
    <div class="col-xs-1">{% bootstrap_button content="Save" icon="star" button_type="submit" button_class="btn-primary" %}</div>
</form>
</div>
</div>

<!-- disable the submit button when the form is submitted to avoid having the user clicking multiple times during page reload (and hence submitting duplicates) -->
<script type="text/javascript">
$(function() {
  $("form").submit(function(e) {
    $("form[name='main-form'] button[type='submit']").prop("disabled","disabled");
    $("form[name='main-form'] button[type='submit']").html("Saving order...");
  });
});
</script>

{{ form.media.js }}
{% endblock %}

zipline_app/templates/zipline_app/order/order_list.html
{% extends "zipline_app/base.html" %}


{% block content %}
{% include 'zipline_app/blotter/_create_modals_order.html' %}
{% include 'zipline_app/blotter/_create_modals_js.html' %}

<div class='row'>
  <div class='col-md-3'>
    <h1>Orders</h1>
  </div>
  <div class='col-md-9 text-right'>
    <button data-toggle="modal" data-target="#orders-new" class='btn btn-primary'>
      Create
      <span class="glyphicon glyphicon-plus"></span>
    </button>
  </div>
</div>

    <div class="row">
      <div class="col-xs-1 text-right">ID</div>
      <div class="col-xs-2">Time</div>
      <div class="col-xs-1">Asset</div>
      <div class="col-xs-1">Limit price</div>
      <div class="col-xs-1">Side</div>
      <div class="col-xs-1 text-right">Qty</div>
      <div class="col-xs-1">Account</div>
      <div class="col-xs-1">Comments</div>
      <div class="col-xs-1">User</div>
      <div class="col-xs-1">Status</div>
      <div class="col-xs-1">Validity</div>
    </div>

    {% for order in order_list %}
    <div class="row">
      <div class="col-xs-1 text-right">
        <a href="{% url 'zipline_app:orders-detail' order.id %}">#{{ order.id }}</a>
      </div>
      <div class="col-xs-2">{{ order.pub_date|date:"Y-m-d H:i:s" }}</div>
      <div class="col-xs-1">
        <a href="{% url 'zipline_app:assets-detail' order.asset.id %}">{{ order.asset.asset_symbol }}</a>
      </div>
      <div class="col-xs-1">
        {% if order.order_type == "L" %}
        {{ order.limit_price }}
        {% else %}
        &nbsp;
        {% endif %}
      </div>
      <div class="col-xs-1">{{ order.get_order_side_display }}</div>
      <div class="col-xs-1 text-right">{{ order.order_qty_unsigned }}</div>
      <div class="col-xs-1">
        <a href="{% url 'zipline_app:accounts-detail' order.account.id %}">{{ order.account.account_symbol }}</a>
      </div>
      <div class="col-xs-1">{{ order.order_text }}</div>
      <div class="col-xs-1">{{ order.user.username }}</div>
      <div class="col-xs-1">
        {{ order.get_order_status_display }}
      </div>
      <div class="col-xs-1">
        {{ order.get_order_validity_display }}
        {% if order.order_validity == 'D' %}
        ({{order.validity_date.date|date:'Y-m-d'}})
        {% endif %}
      </div>
    </div>
{% empty %}
    <div class="alert alert-info">No orders yet.</div>
{% endfor %}

{% endblock %}